### ISSUE TITLE
Создание проекта выдает ошибку

### ISSUE THREAD

**Issue by SchDen** [Bashka/vim_prj#1]
Пытаюсь создать проект командой VimPrjCreate.
Получаю ошибку: e464 ambiguous use of user-defined command.
Пробовал удаять и устанавливать по новой (через ваш же менеджер плагинов).
Пробовал на Elementary OS Freya (Форк Ubuntu).

**Comment by Bashka** [comment]
Такая ошибка может возникнуть только в случае, если существует еще одна команда с именем VimPrjCreate...
Выполните, пожалуйста, команду :command VimPrj и напишите результат.

**Comment by SchDen** [comment]
![screenshot from 2015-06-15 16 22 20](https://cloud.githubusercontent.com/assets/1484977/8160761/fc081dbe-137a-11e5-9944-526ae458a2a6.png)

**Comment by Bashka** [comment]
К сожалению, не могу повторить у себя эту ошибку.

**Comment by SchDen** [comment]
Ох, простите мою глупость, дело в том, что когда я набирал VimPr - автодополнение показывало мне варианты и выделяло оно как раз парвильный вариант, и видимо в силу малой практики, думал, что при нажатии Enter должна примениться нужная команда, но как оказалось, необходимо нажать еще раз Tab, тогда команда отобразиться полностью и после этого Enter (без этого вим применяет команду VimPr и видимо не находит ее, но ошибка какая то не информативная).
Так что все отлично, все нужные файлы создались

**Comment by Bashka** [comment]
Ничего страшного. Пишите если что.
