### ISSUE TITLE
Открытие сохраненного проекта (сессии) - визуальные проблемы

### ISSUE THREAD

**Issue by SchDen** [Bashka/vim_prj#3]
При открытии проекта из сессии наблюдается проблемы с плагином vim-airline, в следствии чего именно не берусь утверждать.

**Вид редактора при простом открытии:**
![screenshot from 2015-06-15 18 40 16](https://cloud.githubusercontent.com/assets/1484977/8163890/70e165ec-138e-11e5-8d73-856ba2a3532d.png)

**Вид редактора после востановления из сессии (просто открытие gvim в папке с проетком (не из vim_start - там вроде бы открывается нормально):**
![screenshot from 2015-06-15 18 47 10](https://cloud.githubusercontent.com/assets/1484977/8163981/f60fdaf0-138e-11e5-843c-89829dac8228.png)

vim-airline как будто не подгрузился, если затем добаить окно сплитом - у нижней полоски статуса и прочей информации цвета и "формы" появляются, но верхняя, с буферами, так и остается без "форм"

**Comment by Bashka** [comment]
Не знаком с этим плагином. Возможно в будущем протестирую предложенную связку.
